version: '3'
services:
  coachbuddy-mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:80"  # Mapowanie portu aplikacji na porcie 8080
      - "8081:443" # Mapowanie portu HTTPS na porcie 8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro  # Mapowanie UserSecrets
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  # Mapowanie HTTPS certyfikaty
